#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /config/www/img

# copy defaults if missing
if [[ ! -f /config/www/index.html ]]; then
    cp /app/www/public/index.html.bak /config/www/index.html
fi
if [[ ! -f /config/www/config.json ]]; then
    cp /app/www/public/config.json.bak /config/www/config.json
fi
if [[ ! -f /config/www/settings.json ]]; then
    cp /app/www/public/settings.json.bak /config/www/settings.json
fi
if [[ ! -f /config/www/server-list.json ]]; then
    cp /app/www/public/server-list.json.bak /config/www/server-list.json
fi

# create symlinks
if [[ ! -L /app/www/public/index.html ]]; then
    ln -sf /config/www/index.html /app/www/public/index.html
fi
if [[ ! -L /app/www/public/config.json ]]; then
    ln -sf /config/www/config.json /app/www/public/config.json
fi
if [[ ! -L /app/www/public/settings.json ]]; then
    ln -sf /config/www/settings.json /app/www/public/settings.json
fi
if [[ ! -L /app/www/public/server-list.json ]]; then
    ln -sf /config/www/server-list.json /app/www/public/server-list.json
fi

# update templates
cp /app/www/public/examples/example*.html /config/www/

# use custom js files if exist
if [[ -f /config/www/speedtest.js ]]; then
    cp /config/www/speedtest.js /app/www/public/speedtest.js
fi
if [[ -f /config/www/speedtest_worker.js ]]; then
    cp /config/www/speedtest_worker.js /app/www/public/speedtest_worker.js
fi

# sets apikey for ipinfo.io, if it exists
if [ -n "$IPINFO_APIKEY" ]; then
    sed -i "s/\$IPINFO_APIKEY = .*/\$IPINFO_APIKEY = '${IPINFO_APIKEY:-}';/g" \
    /app/www/public/backend/getIP_ipInfo_apikey.php
fi

# enables custom results page
if [ "$CUSTOM_RESULTS" == "true" ]; then
    echo "custom results"
    if [[ ! -e "/config/www/results/index.php" ]]; then
        mkdir -p /config/www/results/
        mv /app/www/public/results/index.php /config/www/results/index.php
    fi
    ln -sf /config/www/results/index.php /app/www/public/results/index.php
fi

# configure app settings
sed -i "\
    s|\$Sqlite_db_file.*|\$Sqlite_db_file = \'/config/speedtest_telemetry.sql\';|g; \
    s|\$enable_id_obfuscation.*|\$enable_id_obfuscation = true;|g;
    s|\$stats_password.*|\$stats_password = \'${PASSWORD}\';|g" \
    /app/www/public/results/telemetry_settings.php
if [ "$DB_TYPE" = "postgresql" ]; then
    sed -i "\
        s|\$db_type.*|\$db_type = \'${DB_TYPE}\';|g; \
        s|\$PostgreSql_username.*|\$PostgreSql_username = \'${DB_USERNAME}\';|g; \
        s|\$PostgreSql_password.*|\$PostgreSql_password = \'${DB_PASSWORD}\';|g; \
        s|\$PostgreSql_hostname.*|\$PostgreSql_hostname = \'${DB_HOSTNAME}\';|g; \
        s|\$PostgreSql_databasename.*|\$PostgreSql_databasename = \'${DB_NAME}\';|g" \
        /app/www/public/results/telemetry_settings.php
elif [ "$DB_TYPE" = "mysql" ]; then
    sed -i "\
        s|\$MySql_username.*|\$MySql_username = \'${DB_USERNAME}\';|g; \
        s|\$MySql_password.*|\$MySql_password = \'${DB_PASSWORD}\';|g; \
        s|\$MySql_hostname.*|\$MySql_hostname = \'${DB_HOSTNAME}\';|g; \
        s|\$MySql_databasename.*|\$MySql_databasename = \'${DB_NAME}\';|g; \
        s|\$MySql_port.*|\$MySql_port = \'${DB_PORT:-3306}\';|g" \
        /app/www/public/results/telemetry_settings.php
else
    sed -i \
        "s|\$db_type.*|\$db_type = \'sqlite\';|g" \
        /app/www/public/results/telemetry_settings.php
fi

# permissions
lsiown -R abc:abc \
    /config
